# Generated by Django 2.1.15 on 2021-02-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210210_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='agent',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.FloatField(),
        ),
    ]
