# Generated by Django 2.2.10 on 2021-02-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210210_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='owner',
        ),
        migrations.AlterField(
            model_name='sales',
            name='agent',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='sales',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sales',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
