# Generated by Django 2.2.10 on 2021-02-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20210211_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='firmuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='firmuser',
            name='phone',
        ),
    ]
