# Generated by Django 2.2.10 on 2021-02-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20210211_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmuser',
            name='gstin',
            field=models.CharField(default='', max_length=100),
        ),
    ]
